# Generated by Django 3.1.2 on 2021-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('shop', models.ManyToManyField(to='MyShopManage.ShopList')),
            ],
        ),
        migrations.CreateModel(
            name='Shopemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('shop', models.ManyToManyField(to='MyShopManage.ShopList')),
            ],
        ),
    ]
