# Generated by Django 3.1.2 on 2021-04-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopManage', '0003_auto_20210413_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLevel',
        ),
    ]
