# Generated by Django 3.1.2 on 2021-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopManage', '0004_delete_accesslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopemployee',
            name='manager',
            field=models.ManyToManyField(to='MyShopManage.ShopManager'),
        ),
    ]
