# Generated by Django 3.1.2 on 2021-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopManage', '0005_shopemployee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopemployee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
